// AUTO-GENERATED BY scripts/generate_domain.py

import 'package:dio/dio.dart';
import 'package:lib_gestion_ets_flutter/src/serializers.dart';
import 'package:lib_gestion_ets_flutter/src/api/catalogo_controller_api.dart';
import 'package:lib_gestion_ets_flutter/src/api/administrador_api.dart';
import 'package:lib_gestion_ets_flutter/src/api/alumno_controller_api.dart';
import 'package:lib_gestion_ets_flutter/src/api/perfil_api.dart';
import 'models.dart';

class EtsService {
  final CatalogoControllerApi _catalogo_controller;
  final AdministradorApi _administrador;
  final AlumnoControllerApi _alumno_controller;
  final PerfilApi _perfil;

  EtsService(Dio dio)
      :     _catalogo_controller = CatalogoControllerApi(dio, standardSerializers),
            _administrador = AdministradorApi(dio, standardSerializers),
            _alumno_controller = AlumnoControllerApi(dio, standardSerializers),
            _perfil = PerfilApi(dio, standardSerializers);
}