// AUTO-GENERATED BY scripts/generate_domain.py

class AsignarPeriodo {
  final String? nombre;
  final String? fechaInicio;
  final String? fechaFin;
  final int? idTipoEts;
  const AsignarPeriodo({this.nombre, this.fechaInicio, this.fechaFin, this.idTipoEts});
}

class Aula {
  final int? id;
  final String? clave;
  final String? edificio;
  const Aula({this.id, this.clave, this.edificio});
}

class CambiarNombre {
  final String? nombre;
  final String? primerApellido;
  final String? segundoApellido;
  const CambiarNombre({this.nombre, this.primerApellido, this.segundoApellido});
}

class CambiarPassword {
  final String? passwordActual;
  final String? passwordNueva;
  final String? passwordConfirmacion;
  const CambiarPassword({this.passwordActual, this.passwordNueva, this.passwordConfirmacion});
}

class Carrera {
  final int? id;
  final String? clave;
  final String? nombre;
  const Carrera({this.id, this.clave, this.nombre});
}

class CarreraDashboard {
  final int? id;
  final String? nombre;
  final int? totalExamenes;
  const CarreraDashboard({this.id, this.nombre, this.totalExamenes});
}

class Catalogo {
  final int? id;
  final String? nombre;
  const Catalogo({this.id, this.nombre});
}

class CrearAula {
  final String? clave;
  final String? edificio;
  const CrearAula({this.clave, this.edificio});
}

class CrearCarrera {
  final String? clave;
  final String? nombre;
  const CrearCarrera({this.clave, this.nombre});
}

class CrearExamen {
  final int? idMateria;
  final int? idDocente;
  final int? idAula;
  final int? idTurno;
  final int? idTipoEts;
  final String? fechaAplicacion;
  const CrearExamen({this.idMateria, this.idDocente, this.idAula, this.idTurno, this.idTipoEts, this.fechaAplicacion});
}

class Dashboard {
  final dynamic periodo;
  final int? totalExamenes;
  final int? totalCarreras;
  final int? totalSalones;
  final List<CarreraDashboard>? examenesPorCarrera;
  const Dashboard({this.periodo, this.totalExamenes, this.totalCarreras, this.totalSalones, this.examenesPorCarrera});
}

class DetalleEts {
  final int? id;
  final String? materia;
  final String? plan;
  final String? fecha;
  final String? hora;
  final String? turno;
  final String? salon;
  final String? evaluador;
  final String? carrera;
  final bool? guardado;
  const DetalleEts({this.id, this.materia, this.plan, this.fecha, this.hora, this.turno, this.salon, this.evaluador, this.carrera, this.guardado});
}

class EditarAula {
  final int? id;
  final String? clave;
  final String? edificio;
  const EditarAula({this.id, this.clave, this.edificio});
}

class EditarCarrera {
  final int? id;
  final String? clave;
  final String? nombre;
  const EditarCarrera({this.id, this.clave, this.nombre});
}

class EditarExamen {
  final int? idEts;
  final int? idMateria;
  final int? idDocente;
  final int? idAula;
  final int? idTurno;
  final int? idTipoEts;
  final String? fechaAplicacion;
  const EditarExamen({this.idEts, this.idMateria, this.idDocente, this.idAula, this.idTurno, this.idTipoEts, this.fechaAplicacion});
}

class EditarPeriodo {
  final int? idPeriodo;
  final String? nombre;
  final String? fechaInicio;
  final String? fechaFin;
  const EditarPeriodo({this.idPeriodo, this.nombre, this.fechaInicio, this.fechaFin});
}

class EtsDTO {
  final int? id;
  final String? materia;
  final String? maestro;
  final String? fecha;
  final String? salon;
  const EtsDTO({this.id, this.materia, this.maestro, this.fecha, this.salon});
}

class EtsProximosDTO {
  final int? idEtsAgenda;
  final int? idEts;
  final String? materia;
  final String? fechaHora;
  final int? diasRestantes;
  const EtsProximosDTO({this.idEtsAgenda, this.idEts, this.materia, this.fechaHora, this.diasRestantes});
}

class Examen {
  final int? idEts;
  final int? idMateria;
  final String? nombreMateria;
  final int? idDocente;
  final String? nombreDocente;
  final int? idAula;
  final String? claveAula;
  final int? idTurno;
  final String? nombreTurno;
  final int? idTipoEts;
  final String? fechaAplicacion;
  const Examen({this.idEts, this.idMateria, this.nombreMateria, this.idDocente, this.nombreDocente, this.idAula, this.claveAula, this.idTurno, this.nombreTurno, this.idTipoEts, this.fechaAplicacion});
}

class GetExamen {
  final int? idEts;
  final int? idMateria;
  final int? idDocente;
  final int? idCarrera;
  final int? semestre;
  final int? idAula;
  final int? idTurno;
  final int? idTipoEts;
  final String? fechaAplicacion;
  const GetExamen({this.idEts, this.idMateria, this.idDocente, this.idCarrera, this.semestre, this.idAula, this.idTurno, this.idTipoEts, this.fechaAplicacion});
}

class LocalDateTime {
  const LocalDateTime({});
}

class MateriaEtsDTO {
  final String? nombreUsuario;
  final String? avatar;
  final String? fecha;
  final int? duracionDias;
  final List<EtsProximosDTO>? ets;
  const MateriaEtsDTO({this.nombreUsuario, this.avatar, this.fecha, this.duracionDias, this.ets});
}

class Paginacion {
  final int? numeroPagina;
  final int? cantidadFilas;
  const Paginacion({this.numeroPagina, this.cantidadFilas});
}

class Perfil {
  final String? nombre;
  final String? primerApellido;
  final String? segundoApellido;
  final String? email;
  const Perfil({this.nombre, this.primerApellido, this.segundoApellido, this.email});
}

class Periodo {
  final int? idPeriodo;
  final String? nombre;
  final String? fechaInicio;
  final String? fechaFin;
  final bool? periodoYaComenzo;
  final int? examenesAfectados;
  const Periodo({this.idPeriodo, this.nombre, this.fechaInicio, this.fechaFin, this.periodoYaComenzo, this.examenesAfectados});
}

class SalonEtsDTO {
  final String? salon;
  final String? edificio;
  final bool? editar;
  final bool? eliminar;
  const SalonEtsDTO({this.salon, this.edificio, this.editar, this.eliminar});
}
