import yaml
import os

PACKAGE_NAME = 'lib_gestion_ets_flutter'

with open('openapi.yaml', 'r') as f:
    spec = yaml.safe_load(f)

schemas = spec.get('components', {}).get('schemas', {})
paths = spec.get('paths', {})

# --- Generar models.dart ---
models_lines = []
for name, schema in schemas.items():
    props = schema.get('properties', {})
    fields = []
    for prop, info in props.items():
        t = info.get('type', 'dynamic')
        is_array = t == 'array'
        if is_array:
            ref = info.get('items', {}).get('$ref', '')
            inner = ref.split('/')[-1] if ref else 'dynamic'
            dart_type = f'List<{inner}>?'
        else:
            dart_type = {
                'integer': 'int?',
                'string': 'String?',
                'boolean': 'bool?',
                'number': 'double?',
            }.get(t, 'dynamic')
        fields.append((prop, dart_type))

    lines = [f'class {name} {{']
    for prop, dtype in fields:
        lines.append(f'  final {dtype} {prop};')

    constructor_params = ', '.join([f'this.{p}' for p, _ in fields])
    lines.append(f'  const {name}({{{constructor_params}}});')
    lines.append('}')
    lines.append('')
    models_lines.extend(lines)

os.makedirs('lib/src/domain', exist_ok=True)
with open('lib/src/domain/models.dart', 'w') as f:
    f.write('// AUTO-GENERATED BY scripts/generate_domain.py\n\n')
    f.write('\n'.join(models_lines))

# --- Generar ets_service.dart ---
# Agrupar endpoints por tag
tag_endpoints = {}
for path, methods in paths.items():
    for method, info in methods.items():
        if method not in ['get', 'post', 'put', 'delete', 'patch']:
            continue
        tags = info.get('tags', ['Default'])
        tag = tags[0].replace(' ', '')
        if tag not in tag_endpoints:
            tag_endpoints[tag] = []
        tag_endpoints[tag].append((method, path, info))

service_lines = [
    '// AUTO-GENERATED BY scripts/generate_domain.py',
    '',
    "import 'package:dio/dio.dart';",
    f"import 'package:{PACKAGE_NAME}/src/serializers.dart';",
]

for tag in tag_endpoints:
    snake = ''.join(['_' + c.lower() if c.isupper() else c for c in tag]).lstrip('_')
    service_lines.append(f"import 'package:{PACKAGE_NAME}/src/api/{snake}_api.dart';")

service_lines += [
    "import 'models.dart';",
    '',
    'class EtsService {',
]

# Campos
for tag in tag_endpoints:
    snake = ''.join(['_' + c.lower() if c.isupper() else c for c in tag]).lstrip('_')
    service_lines.append(f'  final {tag}Api _{snake};')

service_lines.append('')
service_lines.append('  EtsService(Dio dio)')

init_lines = []
for tag in tag_endpoints:
    snake = ''.join(['_' + c.lower() if c.isupper() else c for c in tag]).lstrip('_')
    init_lines.append(f'    _{snake} = {tag}Api(dio, standardSerializers)')

service_lines.append('      : ' + ',\n        '.join(init_lines) + ';')
service_lines.append('}')

with open('lib/src/domain/ets_service.dart', 'w') as f:
    f.write('\n'.join(service_lines))

with open('lib/ets_service.dart', 'w') as f:
    f.write(f"export 'src/domain/models.dart';\nexport 'src/domain/ets_service.dart';\n")

print('Domain generated successfully')